### ISSUE TITLE
Suggestion: Add default value for parse options

### ISSUE THREAD

**Issue by prikha** [lib-ruby-parser/ruby-bindings#17]
In a nutshell: 

`LibRubyParser.parse(code, {})` vs `LibRubyParser.parse(code)`

Noticed it's a bit irritating specifying an empty options hash every time `LibRubyParser.parse` is called. Especially when compared to existing tools which all follow a slim interface:

```
Parser::RubyCurrent.parse(str)
SyntaxTree.parse(str)
RubyVM::AbstractSyntaxTree.parse(str)
Ripper.parse(str)
```

**Comment by iliabylich** [comment]
Yes, totally agree.

Either [this line](https://github.com/lib-ruby-parser/ruby-bindings/blob/master/main.c#L61) could be changed so that `rb_parse` is called with `int args, VALUE* argv` and something like `options ||= {}` is called on C side or a Ruby wrapper could be build around `parse` method (that under the hood calls current `parse` method with `options ||= {}`) . Feel free to send a PR, otherwise I'll do it myself next week.

**Comment by prikha** [comment]
Struggling with the PR...

**Comment by prikha** [comment]
Do I get it right that I need you to share the build artifact as in previous one to properly test it?

**Comment by iliabylich** [comment]
> Do I get it right that I need you to share the build artifact as in previous one to properly test it?

no, should be ok as is. I was asking to check it just to be sure that cross-compilation works
